version: '2'
services:
  web:
    image: node:11
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/

    # command: bash -c "chmod +x wait-for-it.sh

    command: bash -c "chmod +x wait-for-it.sh
                      && ./wait-for-it.sh  mysql2:3306 -t 0 --strict
                      && npm install -g nodemon
                      && npm install
                      && nodemon --exec \"node server -d\""
    ports:
     - 3000:3000
  # memcached:
  #   image: memcached:1.4
  #   ports:
  #     - "11212:11211"

  mysql2:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: assists
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: --local-infile --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    #network_mode: "host"
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  #   container_name: mysql
